// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvkzubgsvbhqefsyrwwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2a3p1YmdzdmJocWVmc3lyd3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTMzNDMsImV4cCI6MjA2OTk4OTM0M30.sVb0N83V4bp1oGYlIN5YVY_mDdAU5zprplbH2ccrUgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});